###
//смотрим запись
GET http://localhost:9999/api/posts/show?id=1


###
//удаляем запись
DELETE http://localhost:9999/api/posts/del?id=1


###

//Добавляем запись
POST http://localhost:9999/api/posts
Content-Type: application/json

{
  "id": 0,
  "content": "Last Post3"
}

